//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoBrowser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoBrowser.ConfigData", typeof(ConfigData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAMEWORK TEMPLATE.
        /// </summary>
        internal static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string AUTHENTICATION_TYPE {
            get {
                return ResourceManager.GetString("AUTHENTICATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bgcolor=&quot;#ffc000&quot;.
        /// </summary>
        internal static string BGCOLOR {
            get {
                return ResourceManager.GetString("BGCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bgcolor=&quot;#d9d9d9&quot;.
        /// </summary>
        internal static string BGCOLOR_ANOTHER {
            get {
                return ResourceManager.GetString("BGCOLOR_ANOTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string BLUE_VALUE {
            get {
                return ResourceManager.GetString("BLUE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào, &lt;br /&gt;
        ///
        ///Bạn đã yêu cầu tạo mật khẩu mới. Bên dưới là thông tin chi tiết &lt;br /&gt;&lt;br /&gt;
        ///&lt;table border=&quot;1&quot; cellspacing=&quot;6&quot; cellpadding=&quot;6&quot; style=&quot;border-collapse:collapse;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td bgcolor=&quot;#D8D8D8&quot;&gt;
        ///            Họ tên
        ///        &lt;/td&gt;
        ///        &lt;td&gt;
        ///            {__FIRST__NAME__} {__LAST__NAME__}
        ///        &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///        &lt;td bgcolor=&quot;#D8D8D8&quot;&gt;
        ///            RA Code
        ///        &lt;/td&gt;
        ///        &lt;td&gt;
        ///            {__RA__CODE__}
        ///        &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BODY_FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("BODY_FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;2&quot;.
        /// </summary>
        internal static string BORDER_TABLE {
            get {
                return ResourceManager.GetString("BORDER_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to border=&quot;1&quot; cellspacing=&quot;1&quot; cellpadding=&quot;2&quot;.
        /// </summary>
        internal static string BORDER_TABLE_PDF {
            get {
                return ResourceManager.GetString("BORDER_TABLE_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string BRANCH_GROUP_NAME {
            get {
                return ResourceManager.GetString("BRANCH_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN.
        /// </summary>
        internal static string BRANCH_PREFIX {
            get {
                return ResourceManager.GetString("BRANCH_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\.
        /// </summary>
        internal static string BREAK_FOLDER {
            get {
                return ResourceManager.GetString("BREAK_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string BREAKE_CELL_LINE {
            get {
                return ResourceManager.GetString("BREAKE_CELL_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string CACHE_EXPIRED_DAY {
            get {
                return ResourceManager.GetString("CACHE_EXPIRED_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cat_large_.
        /// </summary>
        internal static string CATE_IMAGE_LARGE_PREFIX {
            get {
                return ResourceManager.GetString("CATE_IMAGE_LARGE_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cat_medium_.
        /// </summary>
        internal static string CATE_IMAGE_MEDIUM_PREFIX {
            get {
                return ResourceManager.GetString("CATE_IMAGE_MEDIUM_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cat_small_.
        /// </summary>
        internal static string CATE_IMAGE_SMALL_PREFIX {
            get {
                return ResourceManager.GetString("CATE_IMAGE_SMALL_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string CATEGORY_GEN_CODE_LENGTH {
            get {
                return ResourceManager.GetString("CATEGORY_GEN_CODE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPFVF Internal Development Team.
        /// </summary>
        internal static string COMMPANY_NAME {
            get {
                return ResourceManager.GetString("COMMPANY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồng Lạc.
        /// </summary>
        internal static string CONTACT_INFO {
            get {
                return ResourceManager.GetString("CONTACT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string CONTRACT_STATUS_CANCEL {
            get {
                return ResourceManager.GetString("CONTRACT_STATUS_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string CONTRACT_STATUS_CHECKING {
            get {
                return ResourceManager.GetString("CONTRACT_STATUS_CHECKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string CONTRACT_STATUS_DONE {
            get {
                return ResourceManager.GetString("CONTRACT_STATUS_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string CONTRACT_STATUS_NEW {
            get {
                return ResourceManager.GetString("CONTRACT_STATUS_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -3.
        /// </summary>
        internal static string CONTRACT_STATUS_PENDING {
            get {
                return ResourceManager.GetString("CONTRACT_STATUS_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string CONTRACT_STATUS_REJECTED {
            get {
                return ResourceManager.GetString("CONTRACT_STATUS_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string CONTRACT_STATUS_REUPLOADED {
            get {
                return ResourceManager.GetString("CONTRACT_STATUS_REUPLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string COOKIE_EXPIRED_DAYS {
            get {
                return ResourceManager.GetString("COOKIE_EXPIRED_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COOKIE_USER_ID.
        /// </summary>
        internal static string COOKIE_USER_ID {
            get {
                return ResourceManager.GetString("COOKIE_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập đầy đủ thông tin trong 3 nhóm nội dung bên dưới..
        /// </summary>
        internal static string CREATE_SUP_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("CREATE_SUP_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ///        body
        ///        {
        ///            font: normal 13px Tahoma, Verdana, Arial, Helvetica, sans-serif;
        ///        }
        ///        
        ///        a
        ///        {
        ///            color: #c75f3e;
        ///        }
        ///        
        ///        #mytable
        ///        {
        ///            width: 700px;
        ///            padding: 0;
        ///            margin: 0;
        ///        }
        ///        
        ///        caption
        ///        {
        ///            padding: 0 0 5px 0;
        ///            width: 700px;
        ///            font: italic 11px Tahoma, Verdana, Arial, Helvetica, sans-serif;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSS_BODY {
            get {
                return ResourceManager.GetString("CSS_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VND.
        /// </summary>
        internal static string CURRENCY {
            get {
                return ResourceManager.GetString("CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Uploads/Images/Customer.
        /// </summary>
        internal static string CUS_FOLDER_UPLOAD_IMAGES {
            get {
                return ResourceManager.GetString("CUS_FOLDER_UPLOAD_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 450.
        /// </summary>
        internal static string CUS_IMAGE_LARGE_HEIGHT {
            get {
                return ResourceManager.GetString("CUS_IMAGE_LARGE_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 450.
        /// </summary>
        internal static string CUS_IMAGE_LARGE_WIDTH {
            get {
                return ResourceManager.GetString("CUS_IMAGE_LARGE_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120.
        /// </summary>
        internal static string CUS_IMAGE_MEDIUM_HEIGHT {
            get {
                return ResourceManager.GetString("CUS_IMAGE_MEDIUM_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120.
        /// </summary>
        internal static string CUS_IMAGE_MEDIUM_WIDTH {
            get {
                return ResourceManager.GetString("CUS_IMAGE_MEDIUM_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        internal static string CUS_IMAGE_SMALL_HEIGHT {
            get {
                return ResourceManager.GetString("CUS_IMAGE_SMALL_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        internal static string CUS_IMAGE_SMALL_WIDTH {
            get {
                return ResourceManager.GetString("CUS_IMAGE_SMALL_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm:ss.
        /// </summary>
        internal static string DATE_TIME_FORMAT_104 {
            get {
                return ResourceManager.GetString("DATE_TIME_FORMAT_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104.
        /// </summary>
        internal static string DATE_TIME_FORMAT_104_CODE_SQL {
            get {
                return ResourceManager.GetString("DATE_TIME_FORMAT_104_CODE_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd/MM/yyyy HH:mm:ss}.
        /// </summary>
        internal static string DATE_TIME_FORMAT_GRID {
            get {
                return ResourceManager.GetString("DATE_TIME_FORMAT_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd/MM/yyyy}.
        /// </summary>
        internal static string DATE_TIME_FORMAT_GRID_104 {
            get {
                return ResourceManager.GetString("DATE_TIME_FORMAT_GRID_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd/MM/yyyy hh:mm:ss}.
        /// </summary>
        internal static string DATE_TIME_FORMAT_GRID_1041 {
            get {
                return ResourceManager.GetString("DATE_TIME_FORMAT_GRID_1041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DB_CONNECTION_NAME {
            get {
                return ResourceManager.GetString("DB_CONNECTION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DB_DMS_LIVE_NAME {
            get {
                return ResourceManager.GetString("DB_DMS_LIVE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DB_DMS_TEST_NAME {
            get {
                return ResourceManager.GetString("DB_DMS_TEST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DB_PASSWORD {
            get {
                return ResourceManager.GetString("DB_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DB_USERNAME {
            get {
                return ResourceManager.GetString("DB_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Choose--.
        /// </summary>
        internal static string DDL_CHOOSE {
            get {
                return ResourceManager.GetString("DDL_CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string DEFAULT_ACTIVE_STATUS {
            get {
                return ResourceManager.GetString("DEFAULT_ACTIVE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -2.
        /// </summary>
        internal static string DEFAULT_CANCELED_STATUS {
            get {
                return ResourceManager.GetString("DEFAULT_CANCELED_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 480.
        /// </summary>
        internal static string DEFAULT_HEIGHT {
            get {
                return ResourceManager.GetString("DEFAULT_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string DEFAULT_INACTIVE_STATUS {
            get {
                return ResourceManager.GetString("DEFAULT_INACTIVE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string DEFAULT_PENDING_STATUS {
            get {
                return ResourceManager.GetString("DEFAULT_PENDING_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 640.
        /// </summary>
        internal static string DEFAULT_WIDTH {
            get {
                return ResourceManager.GetString("DEFAULT_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DMS_LIVE_URL {
            get {
                return ResourceManager.GetString("DMS_LIVE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bill.
        /// </summary>
        internal static string DOC_TYPE_BILL {
            get {
                return ResourceManager.GetString("DOC_TYPE_BILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb.
        /// </summary>
        internal static string DOC_TYPE_CT {
            get {
                return ResourceManager.GetString("DOC_TYPE_CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb.
        /// </summary>
        internal static string DOC_TYPE_FRB {
            get {
                return ResourceManager.GetString("DOC_TYPE_FRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string DOC_TYPE_ID {
            get {
                return ResourceManager.GetString("DOC_TYPE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picture.
        /// </summary>
        internal static string DOC_TYPE_PIC {
            get {
                return ResourceManager.GetString("DOC_TYPE_PIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bs.
        /// </summary>
        internal static string DOC_TYPE_PS {
            get {
                return ResourceManager.GetString("DOC_TYPE_PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DOMAIN_FULL_NAME {
            get {
                return ResourceManager.GetString("DOMAIN_FULL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMP.
        /// </summary>
        internal static string EMP_GROUP_NAME {
            get {
                return ResourceManager.GetString("EMP_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secret.
        /// </summary>
        internal static string ENCRYPT_SECRET_STRING {
            get {
                return ResourceManager.GetString("ENCRYPT_SECRET_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pdf.
        /// </summary>
        internal static string EXTENSION {
            get {
                return ResourceManager.GetString("EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no_image_medium.jpg.
        /// </summary>
        internal static string FILE_LOGO_IMAGE {
            get {
                return ResourceManager.GetString("FILE_LOGO_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_{1}_{2}.jpg.
        /// </summary>
        internal static string FILE_NAME {
            get {
                return ResourceManager.GetString("FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FILE_SERVER_PATH {
            get {
                return ResourceManager.GetString("FILE_SERVER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc,docx,pdf,xls,xlsx,png,jpg,gif,txt.
        /// </summary>
        internal static string FILE_TYPES {
            get {
                return ResourceManager.GetString("FILE_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png,jpg,gif.
        /// </summary>
        internal static string FILE_TYPES_IMAGES {
            get {
                return ResourceManager.GetString("FILE_TYPES_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0,0} VNĐ.
        /// </summary>
        internal static string FORMAT_CURRENCY {
            get {
                return ResourceManager.GetString("FORMAT_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###,###,###,##0.#0.
        /// </summary>
        internal static string FORMAT_CURRENTCY {
            get {
                return ResourceManager.GetString("FORMAT_CURRENTCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:###,###,###,##0.#0}.
        /// </summary>
        internal static string FORMAT_CURRENTCY_GRID {
            get {
                return ResourceManager.GetString("FORMAT_CURRENTCY_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string FORMAT_DATE {
            get {
                return ResourceManager.GetString("FORMAT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm:ss.
        /// </summary>
        internal static string FORMAT_DATE_TIME {
            get {
                return ResourceManager.GetString("FORMAT_DATE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yyyy hh:mm:ss}.
        /// </summary>
        internal static string FORMAT_FULL_DATETIME {
            get {
                return ResourceManager.GetString("FORMAT_FULL_DATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string FUND_INCOME_GEN_CODE_LENGTH {
            get {
                return ResourceManager.GetString("FUND_INCOME_GEN_CODE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;window.print();&lt;/script&gt;.
        /// </summary>
        internal static string JS_PRINT_PAGE {
            get {
                return ResourceManager.GetString("JS_PRINT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP://vnhqsdc02.hcnet.vn:389.
        /// </summary>
        internal static string LDAP_ADDRESS {
            get {
                return ResourceManager.GetString("LDAP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .txt.
        /// </summary>
        internal static string LOG_FILE_TYPE {
            get {
                return ResourceManager.GetString("LOG_FILE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAIL_BCC {
            get {
                return ResourceManager.GetString("MAIL_BCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dms@homecredit.vn.
        /// </summary>
        internal static string MAIL_BCC_DMS {
            get {
                return ResourceManager.GetString("MAIL_BCC_DMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAIL_BODY {
            get {
                return ResourceManager.GetString("MAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAIL_CC {
            get {
                return ResourceManager.GetString("MAIL_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string MAIL_ENABLE_SSL {
            get {
                return ResourceManager.GetString("MAIL_ENABLE_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAIL_FROM {
            get {
                return ResourceManager.GetString("MAIL_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPFVF Notification.
        /// </summary>
        internal static string MAIL_FROM_DISPLAY_NAME_DMS {
            get {
                return ResourceManager.GetString("MAIL_FROM_DISPLAY_NAME_DMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no_reply@homecredit.vn.
        /// </summary>
        internal static string MAIL_FROM_DMS {
            get {
                return ResourceManager.GetString("MAIL_FROM_DMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string MAIL_IS_HTML_BODY {
            get {
                return ResourceManager.GetString("MAIL_IS_HTML_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAIL_SENDER {
            get {
                return ResourceManager.GetString("MAIL_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAIL_SUBJECT {
            get {
                return ResourceManager.GetString("MAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAIL_TO {
            get {
                return ResourceManager.GetString("MAIL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 102400.
        /// </summary>
        internal static string MAX_LENGTH {
            get {
                return ResourceManager.GetString("MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cookie.
        /// </summary>
        internal static string MEMORY_METHOD {
            get {
                return ResourceManager.GetString("MEMORY_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ file *.xls, *.xlsx. Kích thước file tối đa 5MB..
        /// </summary>
        internal static string MESSAGE_UPLOAD_EXCEL {
            get {
                return ResourceManager.GetString("MESSAGE_UPLOAD_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ file *.png, *.jpg, *.gif. Kích thước file tối đa 5MB..
        /// </summary>
        internal static string MESSAGE_UPLOAD_IMAGE {
            get {
                return ResourceManager.GetString("MESSAGE_UPLOAD_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10240.
        /// </summary>
        internal static string MIN_LENGTH {
            get {
                return ResourceManager.GetString("MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string MONEY_DECIMAL_SEP_MARK {
            get {
                return ResourceManager.GetString("MONEY_DECIMAL_SEP_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string MONEY_THOUSAND_SEP_MARK {
            get {
                return ResourceManager.GetString("MONEY_THOUSAND_SEP_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class=&quot;nobg&quot;.
        /// </summary>
        internal static string NOBG {
            get {
                return ResourceManager.GetString("NOBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NOT_AUTHORIZED_URL {
            get {
                return ResourceManager.GetString("NOT_AUTHORIZED_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Ghi Chú.
        /// </summary>
        internal static string NOTE_MESSAGE_ADD_NOTE {
            get {
                return ResourceManager.GetString("NOTE_MESSAGE_ADD_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ORDER_TOTAL {
            get {
                return ResourceManager.GetString("ORDER_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\Data\PDOC.
        /// </summary>
        internal static string PHYSICAL_FILE_PATH {
            get {
                return ResourceManager.GetString("PHYSICAL_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string RED_VALUE {
            get {
                return ResourceManager.GetString("RED_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYS_ADMIN.
        /// </summary>
        internal static string ROLE_SYS_ADMIN {
            get {
                return ResourceManager.GetString("ROLE_SYS_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYS_AUTHENTICATION_ENABLED.
        /// </summary>
        internal static string ROLE_SYS_AUTHENTICATION_ENABLED {
            get {
                return ResourceManager.GetString("ROLE_SYS_AUTHENTICATION_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYS_PUBLIC_PAGES.
        /// </summary>
        internal static string ROLE_SYS_PUBLIC_PAGES {
            get {
                return ResourceManager.GetString("ROLE_SYS_PUBLIC_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYS_ROLE_PUBLIC.
        /// </summary>
        internal static string ROLE_SYS_ROLE_PUBLIC {
            get {
                return ResourceManager.GetString("ROLE_SYS_ROLE_PUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYS_ROLE_PUBLIC_REGISTERED.
        /// </summary>
        internal static string ROLE_SYS_ROLE_PUBLIC_REGISTERED {
            get {
                return ResourceManager.GetString("ROLE_SYS_ROLE_PUBLIC_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string ROWS_PER_PAGE_DEFAULT {
            get {
                return ResourceManager.GetString("ROWS_PER_PAGE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string SCAN_DOC_STATUS_CANCEL {
            get {
                return ResourceManager.GetString("SCAN_DOC_STATUS_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string SCAN_DOC_STATUS_CHECKING {
            get {
                return ResourceManager.GetString("SCAN_DOC_STATUS_CHECKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string SCAN_DOC_STATUS_DONE {
            get {
                return ResourceManager.GetString("SCAN_DOC_STATUS_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string SCAN_DOC_STATUS_NEW {
            get {
                return ResourceManager.GetString("SCAN_DOC_STATUS_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -3.
        /// </summary>
        internal static string SCAN_DOC_STATUS_PENDING {
            get {
                return ResourceManager.GetString("SCAN_DOC_STATUS_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string SCAN_DOC_STATUS_REJECTED {
            get {
                return ResourceManager.GetString("SCAN_DOC_STATUS_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string SCAN_DOC_STATUS_REUPLOADED {
            get {
                return ResourceManager.GetString("SCAN_DOC_STATUS_REUPLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string SCAN_MISTAKE_STATUS_ACTIVE {
            get {
                return ResourceManager.GetString("SCAN_MISTAKE_STATUS_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -3.
        /// </summary>
        internal static string SCAN_MISTAKE_STATUS_PENDING {
            get {
                return ResourceManager.GetString("SCAN_MISTAKE_STATUS_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string SCAN_STATUS_CANCEL {
            get {
                return ResourceManager.GetString("SCAN_STATUS_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang Xử Lý.
        /// </summary>
        internal static string SCAN_STATUS_CHECKING {
            get {
                return ResourceManager.GetString("SCAN_STATUS_CHECKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn Thành.
        /// </summary>
        internal static string SCAN_STATUS_DONE {
            get {
                return ResourceManager.GetString("SCAN_STATUS_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới Tải.
        /// </summary>
        internal static string SCAN_STATUS_NEW {
            get {
                return ResourceManager.GetString("SCAN_STATUS_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ Duyệt.
        /// </summary>
        internal static string SCAN_STATUS_PENDING {
            get {
                return ResourceManager.GetString("SCAN_STATUS_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không Hợp Lệ.
        /// </summary>
        internal static string SCAN_STATUS_REJECTED {
            get {
                return ResourceManager.GetString("SCAN_STATUS_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải Lại.
        /// </summary>
        internal static string SCAN_STATUS_REUPLOAD {
            get {
                return ResourceManager.GetString("SCAN_STATUS_REUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SEC_EMAIL_DOMAIN {
            get {
                return ResourceManager.GetString("SEC_EMAIL_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select One ---.
        /// </summary>
        internal static string SELECT_ONE {
            get {
                return ResourceManager.GetString("SELECT_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string STATUS_TYPE {
            get {
                return ResourceManager.GetString("STATUS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string SUP_GEN_CODE_LENGTH {
            get {
                return ResourceManager.GetString("SUP_GEN_CODE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCC.
        /// </summary>
        internal static string SUP_PREFIX {
            get {
                return ResourceManager.GetString("SUP_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TESTING_EXCEL_EXPORT_PATH {
            get {
                return ResourceManager.GetString("TESTING_EXCEL_EXPORT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TESTING_EXPORT_PATH {
            get {
                return ResourceManager.GetString("TESTING_EXPORT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TESTING_MAIL_BCC {
            get {
                return ResourceManager.GetString("TESTING_MAIL_BCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TESTING_MAIL_CC {
            get {
                return ResourceManager.GetString("TESTING_MAIL_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TESTING_MAIL_TO {
            get {
                return ResourceManager.GetString("TESTING_MAIL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TESTING_PDF_EXPORT_PATH {
            get {
                return ResourceManager.GetString("TESTING_PDF_EXPORT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5120.
        /// </summary>
        internal static string UPLOAD_IMAGE_MAX_FILE_SIZE {
            get {
                return ResourceManager.GetString("UPLOAD_IMAGE_MAX_FILE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDOC.
        /// </summary>
        internal static string WEBSITE_SUBJECT {
            get {
                return ResourceManager.GetString("WEBSITE_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPF Vietnam Finance.
        /// </summary>
        internal static string WEBSITE_TITLE {
            get {
                return ResourceManager.GetString("WEBSITE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.
        /// </summary>
        internal static string WEBSITE_VERSION {
            get {
                return ResourceManager.GetString("WEBSITE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string YELLOW_VALUE {
            get {
                return ResourceManager.GetString("YELLOW_VALUE", resourceCulture);
            }
        }
    }
}
